libs/util/misc.js
=> Fix web3 / Ropsten provider contract instantiation bug

libs/util/hotel.js
Getting an error without it when using the library in the demo app
=> Add const to estimate in deployContract()

libs/BookingData.js, test/BookingData.js
=> Handle getting guest data for booking when a confirmation was required

libs/BookingData.js, package-lock.json, package.json
- Removes duplicate code
- Properly adds lodash to dependencies
I'm going to try to make tests much faster by using https://www.npmjs.com/package/web3-fake-provider and some other mocking techniques. This is a first step in that direction, I expect many small refactorings and code reorganizations. Faster tests should enable us to make more changes in the library towards an improved, streamlined interface.
=> BookingData: Increases code re-use, decreases coupling

libs/HotelManager.js, test/HotelManager.js
=> Get tx info

libs/HotelManager.js, test/HotelManager.js
=> Create full hotel

libs/BookingData.js, libs/HotelEvents.js, libs/HotelManager.js, libs/User.js, libs/index.js, libs/utils/index.js, libs/utils/validators.js, package.json, test/BookingData.js, test/HotelEvents.js, test/parameter-validators.js
This resolve #44 
Add [Joi](https://github.com/hapijs/joi) as dependency and update Chai from 3.5.0 to 4.1.2
=> Validate function params

.travis.yml, package-lock.json, package.json
- Merge this pull request
- After merging, manually tag the resulting merge commit with v0.1.2
- TravisCI releases package on npmjs
=> chore: Release 0.1.2

docs/reference.md, src/data-model/on-chain-hotel.js, src/data-model/wt-index.js, src/interfaces.js, test/wt-libs/data-model/wt-index.spec.js
Improves type-checking and fixes some inconsistencies.
=> chore: Introduces TransactionOptionsInterface

src/data-model/on-chain-hotel.js, src/data-model/wt-index.js, test/usage.spec.js, test/wt-libs/data-model/on-chain-hotel.spec.js
=> fix(on-chain-hotel): Checks if hotel has address before update and remove

src/data-interfaces.js, src/data-model/on-chain-hotel.js
Brings HotelDescriptionInterface on par with data spec on https://windingtree.github.io/docs/swagger-ui/
=> feature: Adds RoomType interface to HotelDescriptionInterface

test/usage.spec.js, test/wt-libs/data-model/on-chain-hotel.spec.js, test/wt-libs/storage-pointer.spec.js
Just a few minor fixes following our face2face discussion.
=> test: Fix a few omissions in existing tests.

src/contracts.js, src/data-model/on-chain-hotel.js, src/data-model/wt-index.js, src/off-chain-data-client.js, src/remotely-backed-dataset.js, src/storage-pointer.js, src/wallet.js, test/usage.spec.js, test/wt-libs/contracts.spec.js, test/wt-libs/data-model/on-chain-hotel.spec.js, test/wt-libs/data-model/wt-index.spec.js, test/wt-libs/index.spec.js, test/wt-libs/off-chain-data-client.spec.js, test/wt-libs/remotely-backed-dataset.spec.js, test/wt-libs/storage-pointer.spec.js, test/wt-libs/wallet.spec.js
=> style: Makes underscore prefixing consistent across the whole codebase

README.md, src/data-model/index.js, src/data-model/on-chain-hotel.js, src/data-model/wt-index.js, src/index.js, src/interfaces.js, src/off-chain-data-client.js, src/storage-pointer.js, test/usage.spec.js, test/wt-libs/data-model/on-chain-hotel.spec.js, test/wt-libs/data-model/wt-index.spec.js, test/wt-libs/index.spec.js, test/wt-libs/off-chain-data-client.spec.js, test/wt-libs/storage-pointer.spec.js, test/wt-libs/wallet.spec.js
This is based on feat/error-handling branch as I was lazy to deal with conflicts later.
Waits for #158 to be merged
=> Breaking: Changes signature of a few methods to make them async when not necessary

src/contracts.js
...and strips off 200 kB from the build size in the process.
Closes #53 as well
=> feat: Uses Abstract contracts for interaction with WTIndex

CONTRIBUTING.md
=> docs: Adds contributing document

.babelrc, package-lock.json, package.json
Babel started to yell some warnings (see http://babeljs.io/docs/en/env/), so I've updated it.
=> chore: Update dependencies

docs/reference.md, package-lock.json, package.json, src/data-model/on-chain-hotel.js, src/data-model/wt-index.js, src/interfaces.js, test/usage.spec.js, test/utils/test-wallet-2.json, test/wt-libs/data-model/on-chain-hotel.spec.js, test/wt-libs/data-model/wt-index.spec.js
=> feat: Adds transferHotelOwnership

.travis.yml, src/storage-pointer.js, test/wt-libs/storage-pointer.spec.js
=> feat: Throws on duplicate fields in storage pointer initialization

.github/PULL_REQUEST_TEMPLATE/release.md
This will allow creating release PRs in an easier way with a link like this:
https://github.com/windingtree/wt-js-libs/compare/develop...master?expand=1&template=release.md
=> chore: Adds release pull request template

package-lock.json, package.json
=> Greenkeeper/webpack 4.18.0

docs/reference.md, src/data-model/index.js, src/data-model/on-chain-hotel.js, src/utils.js, test/wt-libs/data-model/on-chain-hotel.spec.js, test/wt-libs/utils.spec.js
=> Adds gasMargin option

.gitignore, package-lock.json, src/storage-pointer.js, test/usage.spec.js, test/utils/data/off-chain-data.json, test/wt-libs/storage-pointer.spec.js
=> improvement(model): implement windingtree/wtips#9

docs/reference.md, src/data-model/on-chain-airline.js, src/storage-pointer.js, test/utils/scripts/localtestnet.sh, test/wt-libs/storage-pointer.spec.js
Also rename `Flights.flights` to `Flights.items` to avoid confusion (see https://github.com/windingtree/wiki/pull/83)
=> wtip-003: Make storage pointer work with arrays

package-lock.json, package.json
- Merge this PR with a merge commit.
- Manually tag the resulting merge commit with v0.8.1 and push it to github.
- Travis makes a release from a tagged commit.
- Don't delete the develop branch!
=> Release 0.8.1

docs/reference.md, src/data-model/on-chain-airline.js, src/data-model/on-chain-hotel.js, src/storage-pointer.js, test/wt-libs/storage-pointer.spec.js
https://github.com/windingtree/wtips/issues/10
=> wtip-003: limit storage pointer `toPlainObject` resolving by depth

src/index.js
=> #31: export TrustClueClient

docs/reference.md, package-lock.json, package.json, src/on-chain-data-client/organization-factory.js, src/on-chain-data-client/organization.js, src/on-chain-data-client/remotely-backed-dataset.js, src/on-chain-data-client/segment-directory.js, src/on-chain-data-client/storage-pointer.js, src/on-chain-data-client/updateable-organization.js, src/on-chain-data-client/utils.js, test/on-chain-data-client/organization-factory.spec.js, test/on-chain-data-client/organization.spec.js, test/on-chain-data-client/storage-pointer.spec.js, test/on-chain-data-client/updateable-organization.spec.js, test/usage/integration.spec.js, test/utils/data-hotel-model-definition.js, test/utils/migrations/2_deploy_contracts.js
Adds support for orgJsonHash from https://github.com/windingtree/wt-contracts/pull/258
TODO
=> feat: Adds support for orgJsonHash
